# Generated by Django 6.0.6 on 2026-06-28 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "native_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("AF", "Afrikaans"),
                                ("SQ", "Albanian"),
                                ("AM", "Amharic"),
                                ("AR", "Arabic"),
                                ("HY", "Armenian"),
                                ("AZ", "Azerbaijani"),
                                ("EU", "Basque"),
                                ("BE", "Belarusian"),
                                ("BN", "Bengali"),
                                ("BS", "Bosnian"),
                                ("BG", "Bulgarian"),
                                ("CA", "Catalan"),
                                ("CEB", "Cebuano"),
                                ("ZH", "Chinese"),
                                ("HR", "Croatian"),
                                ("CS", "Czech"),
                                ("DA", "Danish"),
                                ("NL", "Dutch"),
                                ("EN", "English"),
                                ("EO", "Esperanto"),
                                ("ET", "Estonian"),
                                ("FI", "Finnish"),
                                ("FR", "French"),
                                ("GL", "Galician"),
                                ("KA", "Georgian"),
                                ("DE", "German"),
                                ("EL", "Greek"),
                                ("GU", "Gujarati"),
                                ("HT", "Haitian Creole"),
                                ("HA", "Hausa"),
                                ("HAW", "Hawaiian"),
                                ("HE", "Hebrew"),
                                ("HI", "Hindi"),
                                ("HMN", "Hmong"),
                                ("HU", "Hungarian"),
                                ("IS", "Icelandic"),
                                ("IG", "Igbo"),
                                ("ID", "Indonesian"),
                                ("GA", "Irish"),
                                ("IT", "Italian"),
                                ("JA", "Japanese"),
                                ("JW", "Javanese"),
                                ("KN", "Kannada"),
                                ("KK", "Kazakh"),
                                ("KM", "Khmer"),
                                ("KO", "Korean"),
                                ("KU", "Kurdish (Kurmanji)"),
                                ("KY", "Kyrgyz"),
                                ("LO", "Lao"),
                                ("LA", "Latin"),
                                ("LV", "Latvian"),
                                ("LT", "Lithuanian"),
                                ("LB", "Luxembourgish"),
                                ("MK", "Macedonian"),
                                ("MG", "Malagasy"),
                                ("MS", "Malay"),
                                ("ML", "Malayalam"),
                                ("MT", "Maltese"),
                                ("MI", "Maori"),
                                ("MR", "Marathi"),
                                ("MN", "Mongolian"),
                                ("MY", "Myanmar (Burmese)"),
                                ("NE", "Nepali"),
                                ("NO", "Norwegian"),
                                ("NY", "Chichewa"),
                                ("PS", "Pashto"),
                                ("FA", "Persian"),
                                ("PL", "Polish"),
                                ("PT", "Portuguese"),
                                ("PA", "Punjabi"),
                                ("RO", "Romanian"),
                                ("RU", "Russian"),
                                ("SM", "Samoan"),
                                ("GD", "Scots Gaelic"),
                                ("SR", "Serbian"),
                                ("ST", "Sesotho"),
                                ("SN", "Shona"),
                                ("SD", "Sindhi"),
                                ("SI", "Sinhala"),
                                ("SK", "Slovak"),
                                ("SL", "Slovenian"),
                                ("SO", "Somali"),
                                ("ES", "Spanish"),
                                ("SU", "Sundanese"),
                                ("SW", "Swahili"),
                                ("SV", "Swedish"),
                                ("TG", "Tajik"),
                                ("TA", "Tamil"),
                                ("TE", "Telugu"),
                                ("TH", "Thai"),
                                ("TR", "Turkish"),
                                ("UK", "Ukrainian"),
                                ("UR", "Urdu"),
                                ("UZ", "Uzbek"),
                                ("VI", "Vietnamese"),
                                ("CY", "Welsh"),
                                ("XH", "Xhosa"),
                                ("YI", "Yiddish"),
                                ("YO", "Yoruba"),
                                ("ZU", "Zulu"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
