# Generated by Django 6.0.6 on 2026-06-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cardreviewevent",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_events",
                to="cards.card",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="cards",
            field=models.ManyToManyField(
                blank=True, related_name="decks", to="cards.card"
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hierarchyitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="cards.hierarchyitem",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks",
                to="cards.hierarchyitem",
            ),
        ),
        migrations.AddIndex(
            model_name="cardreviewevent",
            index=models.Index(
                fields=["card", "created_at"], name="cards_cardr_card_id_125273_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                fields=("owner", "name", "parent"), name="unique_deck_per_owner_parent"
            ),
        ),
    ]
